### ISSUE TITLE
Change Mirror Plane in UI

### ISSUE THREAD

**Issue by ill** [krathjen/studiolibrary#170]
My character is facing down positive X instead of Y as usual.  It would be great if there was a way to set the mirror plane in the UI.

Thankfully I'm also a programmer and I was able to modify mirrortable.py line 109 to : mirrorPlane=MirrorPlane.XY for now as a workaround.

**Comment by krathjen** [comment]
Hey @ill,

Thanks for the feedback!

Yes, this would be a nice feature.

It might also be nice to add a default var on the MirrorTable class so you don't need to change the default MirrorPlane via code.

Thanks for letting us know.

Kurt

```python
# Code example

import studiolibrary

import mutils
mutils.MirrorTable.DEFAULT_MIRROR_PLANE = mutils.MirrorTable.MirrorPlane.XY

studiolibrary.main()
```

**Comment by krathjen** [comment]
Thanks again for the suggestion.

This option has now been added to the UI in version 2.6.0.b5+
