### ISSUE TITLE
Maya 2018 error

### ISSUE THREAD

**Issue by dlloydwo** [krathjen/studiolibrary#177]
I'm getting this when try to run Studio Library on Maya 2018:

```
# Traceback (most recent call last):
#   File "//slsvr/system/Codebase/Maya/maya2017/scripts/studiolibrary/packages\studioqt\widgets\folderswidget\folderswidget.py", line 875, in filterAcceptsRow
#     index = self.sourceModel().index(sourceRow, 0, sourceParent)
# NotImplementedError: pure virtual method 'QAbstractItemModel.index()' not implemented.
```

and nothing then shows up in the GUI.

**Comment by krathjen** [comment]
Hi @dlloydwo,

Thanks for the comment.

This looks like an old error. What version of the Studio Library are you using?

```python
import studiolibrary
print studiolibrary.version()
```

Cheers,

Kurt

**Comment by dlloydwo** [comment]
Indeed. I was in a bit of a panic yesterday and was sourcing an old version. Everything's fine now!
