### ISSUE TITLE
Updating an Item

### ISSUE THREAD

**Issue by kalemas** [krathjen/studiolibrary#183]
Hi @krathjen 

I found inconvenient the way i would update an item in the library. When i create an item with the same name it ask me to move existing to the trash but No and Cancel have same effect, item stay in place. If i say Yes, it would show me a message  that same item still exist in the trash, and i understand that i have to clean the Trash or rename an item.

May we to leave Ok and Cancel buttons in the Trash dialog and overwriting items in the Trash folder?

![maya_2018-02-21_12-30-57](https://user-images.githubusercontent.com/638393/36472647-727a19b4-1703-11e8-9369-51825312f609.png)
![maya_2018-02-21_12-30-22](https://user-images.githubusercontent.com/638393/36472648-72968932-1703-11e8-8ff7-f3f26565e48a.png)

**Comment by krathjen** [comment]
Hey @kalemas,

I've created a pull request for this.

https://github.com/krathjen/studiolibrary/pull/184

Let me know if this fixes your issue.

Thanks

Kurt

**Comment by krathjen** [comment]
Hey @kalemas,

Just letting you know that I have removed the "No" button in version 2.4.0b2.

Thanks again for the suggestion.

Cheers,

Kurt
