### ISSUE TITLE
The folders aren't showing in Maya 2018?

### ISSUE THREAD

**Issue by krathjen** [krathjen/studiolibrary#196]
Email

> I’m trying out the studio library in maya 2018 and it looks like it’s empty. It worked in 2017, but the asset ui is blank in 2018. Even when I try to create a folder nothing shows up.

Email

>When I try to use it in 2018 the folders aren't showing when I open 2017, it works perfectly fine though... any help or ideas as to why?
 
Email

> I have a problem when I try to create a Folder in Maya 2018. I try it in Maya 2017 and it works, the problem is that I need to use Maya 2018.
> Here's the error:

```python
# folderswidget.py", line 875, in filterAcceptsRow
#     index = self.sourceModel().index(sourceRow, 0, sourceParent)
# NotImplementedError: pure virtual method 'QAbstractItemModel.index()' not implemented.
```

**Comment by krathjen** [comment]
This issue should now be fixed in version 2.2.4.

Please download the latest version from the website. 

Thanks

**Comment by Garciaga74** [comment]
Hello friends, I have the 2.3.4 version in maya 2018 and it looks like it’s empty too. How can I fix it??

**Comment by krathjen** [comment]
Hey @Garciaga74,

Thanks for your comment.

Do you see any error messages in the script editor?

Have you set a root folder for the Studio Library?

Also, what OS are you using? eg: Windows 10?

Thanks,

Kurt

**Comment by Garciaga74** [comment]
Hello thanks for reply. no error messages, and yes, I created a root folder
and the content is inside but it doesn´t show it in Maya, I use Windows 10.

Thanks again


2018-05-12 12:43 GMT+02:00 krathjen <notifications@github.com>:

**Comment by krathjen** [comment]
Hey @Garciaga74,

Thanks for the information. 

I'll try and have a look at this over the next few days.

Cheers,

Kurt

**Comment by Garciaga74** [comment]
Thanks for your help, I send you a picture about how I see the library,
nothing apears..:(
​


2018-05-13 6:15 GMT+02:00 krathjen <notifications@github.com>:

**Comment by Ma7hius** [comment]
I have run into the same Issue with Linux and Version 2.3.4 if StudioLib. Has there been any progress made on this?
Cheers

**Comment by krathjen** [comment]
Hey @wolfman3d & @Ma7hius, 

Thanks for the feedback.

Regarding the folder depth:

You can now set the folder depth via the config file in version[ 2.4.0.b10](https://github.com/krathjen/studiolibrary/releases).

The config file can be found in the following directory. The default is 4.
https://github.com/krathjen/studiolibrary/blob/master/config/default.json

Let me know if you're still having issues.

Thanks,

Kurt

**Comment by krathjen** [comment]
Hey @Garciaga74,

Do you mind testing the latest version from the following releases page?

https://github.com/krathjen/studiolibrary/releases

Make sure you click the sync/refresh button in the top right corner. (See the animated gif attached)

Thanks,

Kurt

![example2](https://user-images.githubusercontent.com/8162617/45094593-1c52d480-b15f-11e8-8b7c-286adfbcb30f.gif)

**Comment by Ma7hius** [comment]
Hey @krathjen,

Thanks for sending through the updated StudioLib, 2.4.0.b10.

Unfortunately, we are still having issues with folders not being displayed on Linux.
We are not going further than 4 folders deep so I have not created a custom config file as you mentioned.

Cheers
Matt

**Comment by thoolaeff** [comment]
on 2.3.4 in Linux I am also having the issue of the studio library not showing folders more than 4 deep.  You can see the issue in the attached gif. The folder named 5 was actually made with the studio library but is not shown in the library. Is there a solution for this or is this a bug that is being worked on?

Thanks for all your help and all your hard work Kurt!

![folderdepth](https://user-images.githubusercontent.com/43421943/47883709-5224da00-ddeb-11e8-86cc-46faaece5f34.gif)

**Comment by krathjen** [comment]
Hey @thoolaeff,

Thanks for the comment.

You can change the "recursiveSearchDepth" in the config file. The default is 4.

https://github.com/krathjen/studiolibrary/blob/master/config/default.json

This was added in version 2.4.0+

Hope that helps,

Kurt

**Comment by thoolaeff** [comment]
oh excellent thanks! do you know when you expect to have a full release of 2.4+ currently it is labeled as a pre release. I would like to roll out your next stable release if you have an eta on that I can plan for rolling it out.

Thanks

**Comment by krathjen** [comment]
Version 2.4.0.b16 is getting close for a stable release if you have any issues with this version just let us know. 

https://github.com/krathjen/studiolibrary/releases/tag/2.4.0.b16

We will be moving on to 2.5.0 features soon. 

Thanks

**Comment by thoolaeff** [comment]
Will do and thanks

**Comment by krathjen** [comment]
Version 2.4.x has been released and should now fix this issue.

Please re-open or create a new issue if you're still having problems.

Thanks,

Kurt

**Comment by bagadonuts** [comment]
I am working in Maya 2020 and suddenly all my folders are empty. I only have 2 folders deep so that shouldn't be the issue. It has been working flawlessly. Not sure what happened. I thought it was just Maya bugging out and I quit Maya and relaunched and still the same thing.  Any ideas? (I am working in Windows 10)
