### ISSUE TITLE
Object Selection in Maya View causes Studio Library Views to disappear

### ISSUE THREAD

**Issue by boredstiff** [krathjen/studiolibrary#199]
Affects versions: 2.3.4+ (f68ec478416a9744fcce92aad3e6fd7f32f5b199)

I don't know if it was happening before this version, I was doing some fixes on 2.4.0b2 and noticed it and then went back and checked on 2.3.4

To reproduce:
0 ) Launch Maya with an empty scene (really, any scene, but an empty scene works)
1 ) Load StudioLibrary
2 ) Click around in StudioLibrary Window
3 ) Select something in Maya's Outliner, like defaultLightSet or defaultObjectSet
4 ) Mouse back over Studio Library and the middle panel and left panel will turn from blue to grey, folder view disappears.

You can press the Panel button in Studio Library (twice) to bring them back, the first time will throw the object deletion traceback:

```
# Traceback (most recent call last):
#   File "[removed]studiolibrary/librarywidget.py", line 1042, in _callback
#     callback()
#   File "[removed]studiolibrary/librarywidget.py", line 2739, in toggleView
#     if studioqt.isControlModifier():
#   File "[removed]studiolibrary/packages/studioqt/cmds.py", line 176, in isControlModifier
#     modifiers = QtWidgets.QApplication.keyboardModifiers()
#   File "[removed]studiolibrary/packages/studiolibrarymaya/basecreatewidget.py", line 315, in selectionChanged
#     def _thumbnailCaptured(self, path):
#   File "[removed]studiolibrary/packages/studiolibrarymaya/basecreatewidget.py", line 240, in updateContains
#     def objectCount(self):
# RuntimeError: Internal C++ object (PySide2.QtWidgets.QLabel) already deleted.
``` 

Here's what it looks like:
![image](https://user-images.githubusercontent.com/3489076/39592551-f39da0ac-4ebb-11e8-8e22-3c8e07a040d2.png)

Maya: 2018.2
OS: Fedora 26
StudioLibrary: 2.3.4 - 2.4.0b2 (that's what was tested)

**Comment by krathjen** [comment]
Hey @alexwidener,

Thanks for submitting this issue.

At the moment I can't seem to recreate the error on windows using Maya 2016 or 2017.  

I'll run some more tests with Maya 2018 soon.

Thanks again.

Kurt

**Comment by effectzero** [comment]
I've run into this as well on OS X (studioLibrary 2.3.4) though with Alex's steps i can't recreate it and the few times its happened I was unable to pinpoint a cause.  Closing the window and reopening fixed it up.   I'll post again if i can recreate.  

OSX 10.12.6 Maya 2017.5

**Comment by krathjen** [comment]
Thanks for the information @effectzero,

I will also test on OSX when I get time.

Cheers,

Kurt

**Comment by krathjen** [comment]
Hey @alexwidener & @effectzero,

Just letting you know that I still haven't seen this error message on windows using Maya 2018.

I'll try and have a look at OSX soon.

Thanks again,

Kurt

**Comment by krathjen** [comment]
Please try the latest version **(2.4.0.b60)**

You can download the latest version from the following link on Github. Click the green download button and follow the install instructions further down the page.

https://github.com/krathjen/studiolibrary

Thanks,

Kurt

**Comment by boredstiff** [comment]
Hi Kurt, 

Just wanted to let you know that it will be a while before I can test with the new version again and report back, I'm not supporting that area of our pipeline right now. I'll let you know how it went when I get back to supporting those artists. If you feel like closing the issue, I can comment whenever I get to it, that's fine.

Thanks,
Alex

**Comment by krathjen** [comment]
Hey Alex,

Thanks for getting back to me. 

I'll probably close this issue for now then, but please re-open the ticket if the issue happens again.

Thanks,

Kurt
