### ISSUE TITLE
Create library config file

### ISSUE THREAD

**Issue by cgzoso** [krathjen/studiolibrary#20]
Have a config file to store settings...

Should there be a hierarchy? ex: Global -> Library -> User->Env Variable?

Some settings:
-  Mirror table tokens
-  Browser app (Konqueror, Nautilus, Explorer, etc...)
-  Viewport settings for thumbnails
-  Animation format (mb, ma, atom, abc, etc...)
-  Default namespace option

**Comment by krathjen** [comment]
Closing this as we have added a basic config file for now.
