### ISSUE TITLE
Having locked BaseAnimation layer causes no .ma or .mb files to be written when saving animations

### ISSUE THREAD

**Issue by splinecraft** [krathjen/studiolibrary#202]
Noticed an issue that took a little bit to figure out; if saving an animation with animation layers present and if BaseAnimation is locked (not the current layer being saved) it looks as if everything worked okay but there is no .ma/.mb saved in the animation's folder. Could be a nice QoL addition to have a check and message if trying to save an animation with BaseAnimation locked.

**Comment by splinecraft** [comment]
Just a follow up it seems like this can happen when any layer is locked and/or the keying mode under Options is not set to Hybrid.

**Comment by krathjen** [comment]
Hey @splinecraft,

Thanks for submitting the issue and sorry it has taken so long to reply.

I can recreate the issue when the selected animation layer is locked, however, I couldn't recreate the issue when not in Hybrid mode.

In version 2.4.0.b10 it will now show a prompt if the selected animation layer is locked.

I might also add another check/warning if any animation layers are locked.

Let me know what you think.

Thanks,

Kurt

**Comment by krathjen** [comment]
Closing this ticket as the change is now on the master branch.
