### ISSUE TITLE
UI won’t load correctly if Studio Library in a path containing $ (Windows)

### ISSUE THREAD

**Issue by UnaiM** [krathjen/studiolibrary#203]
Hi,

Because of how our server is laid out, I’m supposed to put Studio Library inside a folder containing a dollar sign (`$`). We’re Windows based, so the path is something like `\\server\folder$\…\studiolibrary`.

Whenever it sits inside that `folder$`, it doesn’t seem to load the Qt stylesheet properly (or something yielding the same effect): the top bar is the same colour as the rest of the interface, the spacers are the default dotted lines and the font is tiny too. Moreover, each time I close and reopen it, the top icons fade out more and more.

If I move the exact same copy of Studio Library to any path not containing `$`, it works just fine. I’ve also tried moving it into a local path containing `$` and the problem resurfaces. Any ideas about where to look at in the code to avoid this? It’s mandatory that Studio Library lives inside that folder, and removing the `$` is out of the question.

Thanks in advance!

**Comment by krathjen** [comment]
Hi @UnaiM,

Thanks for submitting this issue and sorry for not replying.

I can't seem to recreate this issue with the latest version (2.4.1). I have tested several root paths with the symbol "$" in the name and it seems to work.

Can you please let me know if this is still an issue.

Many thanks,

Kurt

**Comment by UnaiM** [comment]
Thanks for replying Kurt! I think we’re both right— the root path (as in, the path where SL stores poses and clips) doesn’t seem to make a difference. What I meant was the install path (the path to Studio Library itself).

I’ve tested it with every release since 2.3.4 and the issue very much persists. Note that we’ve solved it on our end by simply storing it somewhere else, but it’s a bit annoying as all other Maya tools live under a path with a `$` in the server.

**Comment by krathjen** [comment]
Hey @UnaiM,

Thanks for getting back to me.

Sorry, I should have read your message properly!

I just made an update which will hopefully fix the issue.

Try the latest master version 2.4.5 from the following link.

https://github.com/krathjen/studiolibrary

Please let me know how it goes.

Thanks,

Kurt

**Comment by UnaiM** [comment]
Wow, that was quick! Works beautifully now, thanks a bunch! :)
