### ISSUE TITLE
Mirror upgrade request

### ISSUE THREAD

**Issue by Psekal** [krathjen/studiolibrary#204]
Right now mirror is working on whole animation that is in the file i would be great if we can select range in the timeline that we would like to mirror.

**Comment by costanalobin** [comment]
totally agree, i wanted to suggest the same

**Comment by krathjen** [comment]
Yes, this would be a good addition.

Thanks for the suggestion! 👍

**Comment by krathjen** [comment]
This has now been added in version 2.6.0.b1+.

Please reopen the ticket if you have any issues.

Thanks again for the suggestion,

Kurt
