### ISSUE TITLE
Getting a "ImportError: No Qt binding were found.# error when trying to start it up in Maya 2015 on Windows 10

### ISSUE THREAD

**Issue by NightShadow02** [krathjen/studiolibrary#205]
![2018-07-11 21_56_56-window](https://user-images.githubusercontent.com/24790647/42576915-0a153734-8556-11e8-8f40-8d46ea81dccb.jpg)
![2018-07-09 15_48_49-window](https://user-images.githubusercontent.com/24790647/42576916-0a509090-8556-11e8-8f39-ecae4fecfaa1.jpg)

Please advise.

edit: I got it working with an older version from here: https://github.com/mjmvisser/studiolibrary

Please advise on how I would get the latest version working with my Maya 2015 SP6

**Comment by krathjen** [comment]
If you're still experiencing issues with the latest version, please either reopen this ticket or create a new one. thank you.
