### ISSUE TITLE
folder icon colors not available anymore?v2.3.4

### ISSUE THREAD

**Issue by alfsici** [krathjen/studiolibrary#208]
Any chance to bring the colors for folder back ?
Users library folders and Publish library are hard to distinguish having all the same colors.

**Comment by krathjen** [comment]
Hey @alfsici,

Thanks for the comment.

Folder colors have been added in version 2.6.0.b6+.

You can download version 2.6.0.b6+ from the master branch.

Let us know if you have any issues.

Cheers,

Kurt
