### ISSUE TITLE
Add a config option to allow for paths that start with "."

### ISSUE THREAD

**Issue by serguei-k** [krathjen/studiolibrary#211]
Hi,

Currently there is a check that ignores all paths with a period:
> IGNORE_PATHS = ["/."] # Ignore all paths the start with a "."

In some studio environments these paths are intentional and used for production data including animation/pose libraries.

I propose adding an option to config to disable this check if necessary.
I would be happy to do a pull request if you'd like.

Thanks!

**Comment by krathjen** [comment]
Hey @serguei-k ,

Thanks for the suggestions.

I've pushed this change to the develop branch. Version 2.4.0.b13.

https://github.com/krathjen/studiolibrary/tree/4cafdf09e8adcac7fb1eeb323695375e7e27ae66

Thanks again and feel free to create a pull request in the future,

Kurt

**Comment by serguei-k** [comment]
Thank you!
