### ISSUE TITLE
'ToastWidget' object has no attribute 'setDuration'

### ISSUE THREAD

**Issue by moky20072002** [krathjen/studiolibrary#213]
I get this error when i try to Overshoot an Pose using the Studiolibrary Apply Bar.. i can apply the pose normally.. btu when i try to use the overshoot it crash and gives me this error "'ToastWidget' object has no attribute 'setDuration'"
![error](https://user-images.githubusercontent.com/43992832/46669695-761c4380-cbd0-11e8-9d77-fc788d10dbc3.JPG)

**Comment by krathjen** [comment]
Hi,

Thanks for submitting the issue.

Sorry I cannot recreate this issue on a few versions. Which version are you using?

Thanks,

Kurt

**Comment by krathjen** [comment]
Sorry, I still cannot recreate this issue.

Feel free to reopen this ticket If you're still having issues.

Thanks,

Kurt
