### ISSUE TITLE
Thumbnails seem to be broken/crashing Maya 2016

### ISSUE THREAD

**Issue by LiannaS** [krathjen/studiolibrary#214]
Hello! I left you an email but thought this might be faster. My library currently looks like this: 

![image](https://user-images.githubusercontent.com/44512959/47595836-201cff00-d937-11e8-99a4-e02179ea3a05.png)

For some reason poses save out normally when I ignore the thumbnail function but when I try to save with a thumbnail - my Maya freezes and crashes. 

Not sure if this is related but the following error pops up in my script editor when I launch Studiolibrary for the first time in a fresh Maya session. 

# Warning: studiolibrarymaya.mayalibrarywidget : The "maya.cmds.workspaceControl" command is not supported! #

I have already deleted and re-installed Studiolibrary and Maya. Nothing seems to restore the functionality for me - any suggestions?

**Comment by krathjen** [comment]
Hi,

Thanks for submitting the issue.

Sorry, but I cannot recreate this problem on Windows 10 with Maya 2016/2017/2018. I have also tested the latest stable version 2.3.4 and the latest version 2.4.0.15b without any issues.

Also, that message is a warning and should not be causing an issue. Do you see any errors/tracebacks in the script editor? Have a look further back in the script editor history too.

Cheers,

Kurt

**Comment by krathjen** [comment]
Closing this ticket for now.

Please reopen the issue if you're still having problems.

Also, you could try installing the latest version **(2.4.0.b60)** from the following link on Github. Click the green download button and follow the install instructions further down the page.

https://github.com/krathjen/studiolibrary

Thanks,

Kurt
