### ISSUE TITLE
RuntimeError: Internal C++ object (AnimItem) already deleted.

### ISSUE THREAD

**Issue by thoolaeff** [krathjen/studiolibrary#215]
Maya: 2018.4
Studio Library: 2.3.4
OS: Linux

Steps to reproduce:

Select Animation Item or Pose Item in Studio Library.
Drag it to another directory to move or copy it

Then this error starts before you even choose to move, copy, or cancel and wont stop even after closing studio library or using the refresh in the studio library menu

![studiolibrarymoveerror](https://user-images.githubusercontent.com/43421943/48215626-817d9e80-e337-11e8-8d90-fdc75b8954d6.gif)

I couldn't copy it for you because the script editor just keeps scrolling with continued error messages.

This may already be fixed in 2.4 so i apologize if it is, I'm currently unable to test upcoming versions. 

Thanks

**Comment by krathjen** [comment]
Hey @thoolaeff,

I'm just going through some old tickets.

Have you tried recreating this error with any of the 2.4.0.b+ versions?

If you're still getting the error with version 2.4.0b+, I'll try and have a closer look. 

Thanks,

Kurt

**Comment by krathjen** [comment]
Closing this ticket for now.

Please reopen the ticket If you're still having issues.

Thanks,

Kurt
