### ISSUE TITLE
# Error: line 1: ImportError: file C:/Users/cruz_/Documents/maya/scripts/studiolibrary/packages\studioqt\vendor\Qt.py line 419: No Qt binding were found. # 

### ISSUE THREAD

**Issue by lemnathalia** [krathjen/studiolibrary#216]
im getting this error when running the script to load studio library

# Error: line 1: ImportError: file C:/Users/cruz_/Documents/maya/scripts/studiolibrary/packages\studioqt\vendor\Qt.py line 419: No Qt binding were found. # 

any help appreciated

maya 2016
windows 10

**Comment by krathjen** [comment]
We have updated the Qt.py module to the latest version.

Do you mind testing the latest master version?

Please let us know if you're still having issues.

Thanks,

Kurt

**Comment by krathjen** [comment]
Closing this issue for now.

Please re-open the issue if you're still having troubles.

Thanks,

Kurt
