### ISSUE TITLE
Numeric entry for Blend Pose slider?

### ISSUE THREAD

**Issue by vigialanti** [krathjen/studiolibrary#221]
The blend pose slider is great for getting artistic blending between poses, but there are times that I also want to type in specific values but can't. Maybe this functionality exists already but isn't exposed?

**Comment by krathjen** [comment]
Hey @vigialanti,

Thanks for the feedback.

This is not currently exposed. It would be a good addition to the pose blending options, though.

Cheers,

Kurt

**Comment by krathjen** [comment]
@vigialanti This has now been added in version 2.6.0.b1+.

Please reopen the ticket if you have any issues.

Thanks again for the suggestion,

Kurt
