### ISSUE TITLE
database.json.bak disappears

### ISSUE THREAD

**Issue by danielskovli** [krathjen/studiolibrary#223]
On occasion we get a missing database.json.bak file. From looking briefly at this, one likely culprit is a race condition in cmds.py -> write() #560.

Without having put much testing to this issue yet, it seems plausible to me that the file 'lock' feature and subsequent exception clause has some issues.

I suggest that this may be slightly improved by reading the files to memory instead of relying on various os.rename() calls, because the files may no longer be present on the file system if a race condition occurs

**Comment by krathjen** [comment]
Hey @danielskovli,

Thanks for the feedback.

The "database.json" file is used as a cache and can be rebuilt easily by pressing the sync button.

The current "write()" function is based on a technique called "atomic writing to file". See the following.

https://stackoverflow.com/questions/2333872/atomic-writing-to-file-with-python

Note: This might not be the case depending on the filesystem. 

Let us know how the testing goes.

Thanks,

Kurt

**Comment by danielskovli** [comment]
Hey @krathjen,

Thanks for the extremely quick reply!

We're looking into this issue more thoroughly now, since we were getting plenty errors yesterday, but essentially can't even reproduce the situation today. Seems likely that server load has something to do with all of this.

What seems less and less likely is that we're experiencing a race between two or more clients, I think it's probably a logical fringe case contained within a single user thread.

I'll keep you updated with anything concrete we find. We're using 2.4.0.b11 by the way. I checked your latest commit, and it doesn't seem like the write() function has been altered since then.

PS: do you have a neat way to reload the cmds module (or the whole app) while testing? All my attempts have resulted in super glitchy UI behavior.

Cheers

**Comment by krathjen** [comment]
Thanks for the update @danielskovli,

You can reload all the Studio Library python modules using the following command.

Note: I've only just added this in version 2.4.0b20+.

Also, I've added a new docs.md file with [How to reload for development](https://github.com/krathjen/studiolibrary/blob/master/DOCS.md#gw4un1m)

```python
import studiolibrary
studiolibrary.reload()

import studiolibrary
studiolibrary.main()
```

Thanks again and I hope that helps,

Kurt

**Comment by krathjen** [comment]
Closing this ticket for now.

Please re-open the issue if you're still having problems.

Thanks,

Kurt
