### ISSUE TITLE
can't see any folder

### ISSUE THREAD

**Issue by chtarvador** [krathjen/studiolibrary#226]
Hi,

I'm trying your script, I can create folders but I cannot see them at all in the interface, and I can't see their content
It works correctly until I hit refresh, then the poses I created don't come back
![Capture](https://user-images.githubusercontent.com/34446041/54887877-0658f700-4e98-11e9-9318-7f73b52362c6.JPG)

But the poses are still stored 

version 2.4.0.b41 ; Windows 10

**Comment by krathjen** [comment]
Hey @chtarvador,

This should now be fixed in the latest version.

Can you please try version 2.4.0.b50?

https://github.com/krathjen/studiolibrary/releases/tag/2.4.0.b50

Let us know how it goes.

Thanks,

Kurt

**Comment by chtarvador** [comment]
Hi Kurt,

It works ! You are the man.

Thank you a lot !

**Comment by chtarvador** [comment]
Hi again,

The issue happens as soon as I modify the root path but it looks ok after uninstalling and reinstalling the script. I hope it helps

Cheers !

**Comment by krathjen** [comment]
Hey @chtarvador,

So are you still getting the issue when modifying the root path in the latest version? 

I'm just clarifying because I can't seem to recreate this in the latest version 2.4.0.b50.

Thanks,

Kurt

**Comment by chtarvador** [comment]
Yes, I'm using the latest version 2.4.0.b50.
Maybe I should do something more, delete some files or something ?

Thank you

**Comment by krathjen** [comment]
Hi @chtarvador,

Sorry, I still cannot recreate this issue.

I was just looking at your screenshot again and I noticed that you have some poses under the directory ".studiolibrary".

Folders/Items in these directories are ignored and will not be displayed.

Are you still using the path in the screenshot?

Thanks,

Kurt

**Comment by chtarvador** [comment]
Hi Kurt,

Sorry for the long wait
Indeed, yes I tried to set another path for different type of poses and as you said, they are not displayed

so now, I'm using the same folder for every poses I need

![zrtyuhfgxxgfxgbxfg](https://user-images.githubusercontent.com/34446041/55440172-2333af80-55a7-11e9-8d89-6d3f36becd06.JPG)

but I feel like I'm missing something or doing something wrong.

thank you !

**Comment by krathjen** [comment]
Hey @chtarvador,

Thanks for the information.

It might be an issue with the filtering, so do you mind sending me the full path to one of the poses that are not working?

Also, you could try the latest version 2.4.0.b60. I have made a few small fixes to the folders panel.

Please let me know how it goes.

Thanks,

Kurt

**Comment by chtarvador** [comment]
Hi Kurt,

here is the old path I was using for the poses that didn't work
![plokiujyhbgfv2](https://user-images.githubusercontent.com/34446041/55684140-4fa15000-5948-11e9-89d1-258da70f4300.JPG)

Thank you, I'm going to try the latest version

**Comment by chtarvador** [comment]
![azerhgxvcxfhjkhfg](https://user-images.githubusercontent.com/34446041/55684683-6185f180-594e-11e9-89d6-b386012f33bc.JPG)
It seems to be working ! :)

Thank you very much,

Cheers !

**Comment by krathjen** [comment]
Great! I'm glad to hear its working for you! :)

**Comment by enlargedhousecats** [comment]
I am also encountering an issue where for some reason all my folders and poses are suddenly missing. Could you explain what you did to fix the issue?
