### ISSUE TITLE
 Warning: studiolibrary.widgets.itemswidget.treewidget

### ISSUE THREAD

**Issue by huadingjin** [krathjen/studiolibrary#227]
# Warning: studiolibrary.widgets.itemswidget.treewidget : Cannot set the column setting for the header label "1" #

**Comment by krathjen** [comment]
Thanks for the feedback.

This warning message has now been changed to debug.

https://github.com/krathjen/studiolibrary/commit/39039cc5e59cbba116d4a3180a810f1be79d847d

Let me know If you have any issues.

Thanks,

Kurt
