### ISSUE TITLE
'utf8' codec can't decode 

### ISSUE THREAD

**Issue by Myles75** [krathjen/studiolibrary#228]
Hello team,
Before all thanks for your amazing work I use studio Library every day since a while and I can’t imagine my life without it.
Since a Week I have this bug and I am unable to save any pose or animation to my Library :

mutils.playblast : Renaming 'c:\users\milan\appdata\local\temp\mutils\milàn\icon\thumbnail.0000.jpg' => 'c:\users\milan\appdata\local\temp\mutils\milàn\icon\thumbnail.jpg
// mutils.playblast : Playblasted 'c:\users\milan\appdata\local\temp\mutils\milàn\icon\thumbnail.jpg'
// studiolibrarymaya.baseitem : Saving: E:/WIP/Spiderman/SpiderVerse/SpiderVerseLibrary/Miles Morales/Body/Base.pose
// mutils.transferobject : Saving pose: c:/users/milan/appdata/local/temp\mutils\milàn\Transfer/pose.json
// Error: root : Uncaught exception
Traceback (most recent call last):
  File "D:\Documents\maya\scripts\studiolibrary\packages\studiolibrarymaya\basecreatewidget.py", line 388, in accept
    description=description,
  File "D:\Documents\maya\scripts\studiolibrary\packages\studiolibrarymaya\basecreatewidget.py", line 412, in save
    description=description,
  File "D:\Documents\maya\scripts\studiolibrary\packages\studiolibrarymaya\poseitem.py", line 330, in save
    super(PoseItem, self).save(objects, path=path, iconPath=iconPath, **kwargs)
  File "D:\Documents\maya\scripts\studiolibrary\packages\studiolibrarymaya\baseitem.py", line 442, in save
    t.save(tempPath, **kwargs)
  File "D:\Documents\maya\scripts\studiolibrary\packages\mutils\decorators.py", line 134, in wrapped
    return fn(*args, **kwargs)
  File "D:\Documents\maya\scripts\studiolibrary\packages\mutils\transferobject.py", line 341, in save
    data = self.dump(metadata)[:-1] + ","
  File "D:\Documents\maya\scripts\studiolibrary\packages\mutils\transferobject.py", line 365, in dump
    return json.dumps(data, indent=2)
  File "C:\Program Files\Autodesk\Maya2018\bin\python27.zip\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Program Files\Autodesk\Maya2018\bin\python27.zip\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Program Files\Autodesk\Maya2018\bin\python27.zip\json\encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "C:\Program Files\Autodesk\Maya2018\bin\python27.zip\json\encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "C:\Program Files\Autodesk\Maya2018\bin\python27.zip\json\encoder.py", line 390, in _iterencode_dict
    yield _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 3: unexpected end of data //

I hope you will find what is wrong with it…
Best regards from Paris !

   SALMONA Milàn 
Animator - Designer
www.salmonart.fr

**Comment by krathjen** [comment]
Hey @Myles75,

Thanks for the feedback.

I think the issue is because your user name contains a non-ascii character ```à``` 

"c:\users\milan\appdata\local\temp\mutils\mil```à```n\ico"

I'll also have a look at recreating this issue when I get time.

Thanks,

Kurt

**Comment by Myles75** [comment]
Thanks a lot !
But how can I change that because it is created by studio Library automatically when I do a thumbnail / Screenshot of the pose. Is it using my name of my Windows session ? How can I tell studio lib to use a name without non ascii Character instead of my session name ?
Best regards

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
De : krathjen <notifications@github.com>
Envoyé : Saturday, March 30, 2019 11:02:09 AM
À : krathjen/studiolibrary
Cc : Myles75; Mention
Objet : Re: [krathjen/studiolibrary] 'utf8' codec can't decode (#228)


Hey @Myles75<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMyles75&data=02%7C01%7C%7Cbe1c82c5fb2e492c93c308d6b4f6c71d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636895369325462873&sdata=JT3N07Klsr4fRn%2BvKhM%2B1TeDZfDXXN8uJjRGSZvgGPQ%3D&reserved=0>,

Thanks for the feedback.

I think the issue is because your user name contains a non-ascii character à

"c:\users\milan\appdata\local\temp\mutils\milàn\ico"

I'll also have a look at recreating this issue when I get time.

Thanks,

Kurt

**Comment by krathjen** [comment]
Hey @Myles75,

Yes, it's using your user name in the path for temp directory.

At the moment you cannot change this path. I can add this to the config which might help.

I still would like to test this, as there might be a better solution.

Thanks.

Kurt

**Comment by Myles75** [comment]
Thanks again for quick answer I was looking how to change the playblast mutils of maya but it is not using the same path as studio library so I am lost it is the only plugin wich use my real name even maya use a temp file named « milan » and not « milàn » in the directory. I tried to change my session windows toi but nothing change when studio lib call mutils to generate the icon / thumbnail in temp files it creates a directory with the « à » ...
When studiolib find that path? Because it is a plugin but when did it create and where? Is there a config fil or a python file ?
Best regards

   SALMONA Milàn
www.salmonart.com<http://www.salmonart.com>

Le 30 mars 2019 à 13:29, krathjen <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hey @Myles75<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMyles75&data=02%7C01%7C%7C95bfd11ac070436ffd3d08d6b50b4f85%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636895457507317627&sdata=6WWFYZpiIjsgqHOgZbzeM8e7gov9wy50i%2FiccQpPJpQ%3D&reserved=0>,

Yes, it's using your user name in the path for temp directory.

At the moment you cannot change this path. I can add this to the config which might help.

I still would like to test this, as there might be a better solution.

Thanks.

Kurt

**Comment by krathjen** [comment]
Hey @Myles75,

I've made a few changes to the latest master version 2.4.0.b55 which might help this issue.

https://github.com/krathjen/studiolibrary

**Whats changed in version 2.4.0.b55**

* You can now change the temp directory from the config
* Moved the temp method from mutils to studiolibrary.utils
* Fixed decoding of temp path with non-ascii characters (need to test this)
* Fixed scroll to selection after moving a folder

See the following link for how to manage a custom config. Sorry if its a bit confusing but please let us know how we can improve it. 

https://github.com/krathjen/studiolibrary/tree/master/config

Maybe try removing the {user} from the temp values.

**default**
```
  "tempPath": "{temp}/StudioLibrary/{user}",
```
**to**
```
  "tempPath": "{temp}/StudioLibrary",
```

I hope that helps and please let us know how you go.

Thanks,

Kurt

**Comment by Myles75** [comment]
A thousand of thanks! I download and install it directly!

**Comment by Myles75** [comment]
Hello, so I tried.
I made both a config.json file in the folder  : D:\Documents\maya\scripts\studiolibrary\config  with text : "tempPath": "{temp}/StudioLibrary",
and a env windows named STUDIO_LIBRARY_CONFIG_PATH with the path : D:\Documents\maya\scripts\studiolibrary\config\config.json

I now got this error:

// studiolibrarymaya.basesavewidget : Setting capture menu to True // 
// Error: root : Uncaught exception
Traceback (most recent call last):
  File "D:\Documents\maya\scripts\studiolibrary\src\studiolibrarymaya\baseitem.py", line 62, in showCreateWidget
    widget = cls.CreateWidgetClass(item=cls(), parent=libraryWindow)
  File "D:\Documents\maya\scripts\studiolibrary\src\studiolibrarymaya\basesavewidget.py", line 73, in __init__
    self.setCaptureMenuEnabled(True)
  File "D:\Documents\maya\scripts\studiolibrary\src\studiolibrarymaya\basesavewidget.py", line 477, in setCaptureMenuEnabled
    path = studiolibrary.tempPath("thumbnail.jpg")
  File "D:\Documents\maya\scripts\studiolibrary\src\studiolibrary\utils.py", line 198, in tempPath
    return normPath(os.path.join(formatPath(temp), *args))
  File "D:\Documents\maya\scripts\studiolibrary\src\studiolibrary\utils.py", line 469, in formatPath
    resolvedString = six.u(formatString).format(**kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128) //

**Comment by krathjen** [comment]
Okay, I'll have another look soon.

Thanks for letting us know.

Kurt

**Comment by Myles75** [comment]
By the way, can you explain me why when I am using the official released version it still use my old named windows session with the non ascii letter inside? I don't understand because I changed my windows session name so it should use the new one by default ("user")?

________________________________
De : krathjen <notifications@github.com>
Envoyé : lundi 1 avril 2019 00:19
À : krathjen/studiolibrary
Cc : Myles75; Mention
Objet : Re: [krathjen/studiolibrary] 'utf8' codec can't decode (#228)


Okay, I'll have another look soon.

Thanks for letting us know.

Kurt

**Comment by krathjen** [comment]
Hey @Myles75,

I just made another update which will hopefully fix this issue.

Do you mind trying the latest version (2.4.0.b56) from the following link?

https://github.com/krathjen/studiolibrary

Please let me know how it goes.

Thanks,

Kurt

**Comment by Myles75** [comment]
Oh! Right, si I test 2.4.0.b56 in a few hours and tell you!

   SALMONA Milàn
www.salmonart.com<http://www.salmonart.com>

Le 1 avr. 2019 à 13:57, krathjen <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hey @Myles75<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMyles75&data=02%7C01%7C%7Cb0ee761cee0a4261399108d6b6992cc0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636897166319459751&sdata=VTsCpht68W47wIBhR4W%2FY7ZczJSHOTxa5vzDvL%2B%2Bw2w%3D&reserved=0>,

I just made another update which will hopefully fix this issue.

Do you mind trying the latest version () from the following link?

https://github.com/krathjen/studiolibrary<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkrathjen%2Fstudiolibrary&data=02%7C01%7C%7Cb0ee761cee0a4261399108d6b6992cc0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636897166319459751&sdata=Ag6MMU%2F%2FWyZhdwn1AYOR%2FQL%2BJDmyA9HeSQJycJObFSE%3D&reserved=0>

Please let me know how it goes.

Thanks,

Kurt

**Comment by Myles75** [comment]
Perfect! Version  2.4.0.b56 finally works fine! Tested on all my files it works. So what did you changed since last version?

**Comment by Myles75** [comment]
Thanks again for your fast answers and solution. I can go back to my animation. You scan't imagine how much you saved me, studiolibrary is like a leg for me ahah. Best regards!

**Comment by krathjen** [comment]
Hey @Myles75,

Great! Happy to hear that it's working for you! 👍 

It was an issue with how we were decoding usernames that have non-english characters.

Thanks again for helping us test the latest versions. 

Kurt

**Comment by Salmonart** [comment]
Hey team!
I have this erros since recently :


# Error: UnicodeDecodeError: file D:\Documents\maya\2020\prefs\studiolibrary\src\studiolibrary\utils.py line 574: 'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128)

(Maya 2020.4 on Windows 10)

Kind regards!
