### ISSUE TITLE
More than one object error in StudioLibrary

### ISSUE THREAD

**Issue by chrisrogers3d** [krathjen/studiolibrary#229]
I am trying to transfer a pose between characters.  I get an error saying more than one of these objects in the scene, but when I look at those 12 names, only 2 have multiple objects with the same name.  It also lists a control thats not in the scene at all as having 2+ in the scene.  The other 9 names have only 1 object with that name.

maya 2018.0
windows
latest studioLibrary

i also get errors saying these objects are not in the scene but they are:
# ValueError: No object matches name: ['target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_leftLowerLip_Control', 'target_fluffy:mid_leftcorner_Control', 'target_fluffy:mid_leftUpperLip_Control', 'target_fluffy:mid_upperLip_Control', 'target_fluffy:mid_rightUpperLip_Control', 'target_fluffy:midjaw_Control', 'target_fluffy:rightLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control', 'target_fluffy:mid_mid_rightUpperLip_Control', 'target_fluffy:mid_mid_leftUpperLip_Control', 'target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control', 'target_fluffy:mid_rightcorner_Control', 'target_fluffy:mid_lowerLip_Control']
for o in ['target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_leftLowerLip_Control', 'target_fluffy:mid_leftcorner_Control', 'target_fluffy:mid_leftUpperLip_Control', 'target_fluffy:mid_upperLip_Control', 'target_fluffy:mid_rightUpperLip_Control', 'target_fluffy:midjaw_Control', 'target_fluffy:rightLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control', 'target_fluffy:mid_mid_rightUpperLip_Control', 'target_fluffy:mid_mid_leftUpperLip_Control', 'target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control', 'target_fluffy:mid_rightcorner_Control', 'target_fluffy:mid_lowerLip_Control']:
 
i check that they are actually in the scene:
for o in ['target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_leftLowerLip_Control', 'target_fluffy:mid_leftcorner_Control', 'target_fluffy:mid_leftUpperLip_Control', 'target_fluffy:mid_upperLip_Control', 'target_fluffy:mid_rightUpperLip_Control', 'target_fluffy:midjaw_Control', 'target_fluffy:rightLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control', 'target_fluffy:mid_mid_rightUpperLip_Control', 'target_fluffy:mid_mid_leftUpperLip_Control', 'target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control', 'target_fluffy:mid_rightcorner_Control', 'target_fluffy:mid_lowerLip_Control']:
     print o, pm.ls(o)

results:
the only one thats not in the scene is the target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control [])

target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_leftLowerLip_Control [nt.Transform(u'target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_leftLowerLip_Control')]
target_fluffy:mid_leftcorner_Control [nt.Transform(u'target_fluffy:mid_leftcorner_Control')]
target_fluffy:mid_leftUpperLip_Control [nt.Transform(u'target_fluffy:mid_leftUpperLip_Control')]
target_fluffy:mid_upperLip_Control [nt.Transform(u'target_fluffy:mid_upperLip_Control')]
target_fluffy:mid_rightUpperLip_Control [nt.Transform(u'target_fluffy:mid_rightUpperLip_Control')]
target_fluffy:midjaw_Control [nt.Transform(u'target_fluffy:midjaw_Control')]
target_fluffy:rightLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control [nt.Transform(u'target_fluffy:rightLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control')]
target_fluffy:mid_mid_rightUpperLip_Control [nt.Transform(u'target_fluffy:mid_mid_rightUpperLip_Control')]
target_fluffy:mid_mid_leftUpperLip_Control [nt.Transform(u'target_fluffy:mid_mid_leftUpperLip_Control')]
target_fluffy:leftLowerLip_ControlBuffer|target_fluffy:mid_rightLowerLip_Control []
target_fluffy:mid_rightcorner_Control [nt.Transform(u'target_fluffy:mid_rightcorner_Control')]
target_fluffy:mid_lowerLip_Control [nt.Transform(u'target_fluffy:mid_lowerLip_Control')]

**Comment by chrisrogers3d** [comment]
user error.

**Comment by krathjen** [comment]
Hi,

We're glad you found a solution.

Please let us know If we can make the error message easier for the end user.

Cheers,

Kurt

**Comment by chrisrogers3d** [comment]
The issue was that it reported the array as not being in the scene where it
would be better for troubleshooting to report which item is not in the
scene.

To provide background, it was a character with three heads and the animator
wanted to transfer animation between them. But some controls had the same
leaf node name, so Maya returned "parent|child" to provide a unique name,
so it took me a while to map the names correctly.

User error, but saying which nodes are not present bwould help debugging.
Also, tools to transfer poses based on name substitution.

Thanks for sharing such an important and industry wide tool for free!

Chris
christopher.rogers@wbgames.com
