### ISSUE TITLE
Nothing happens when I try to use any function except for adding a folder (Maya 2018)

### ISSUE THREAD

**Issue by waad-hashem** [krathjen/studiolibrary#230]
Hey guys, 
I have Maya 2018, windows 10 and studio library  v2.4.1
The issue I have is that the studiolib GUI shows fine, but none of the functions (new animation, anew pose, new selection set ..etc) work..
I can create new folders and that's it..
No error shows ...

**Comment by krathjen** [comment]
Hi @waad-hashem,

Thanks for submitting this issue.

Unfortunately, I cannot recreate the issue. 

Do you see any errors in the script editor?

Also, have you tried the latest version (v2.4.4)? 

If not, you can click the green "Clone or Download" button and following the installation instructions further down the page.

https://github.com/krathjen/studiolibrary

Let me know how it goes.

Thanks,

Kurt

**Comment by krathjen** [comment]
Hi @waad-hashem,

Do you mind testing the latest version 2.4.9?

We made some changes which might fix this issue.

Please let us know how you go.

Thanks,

Kurt

**Comment by krathjen** [comment]
Closing this ticket for now.

Please re-open the issue if you're still having troubles.

Thanks,

Kurt
