### ISSUE TITLE
Maya Docs on loading incorrect.

### ISSUE THREAD

**Issue by tokejepsen** [krathjen/studiolibrary#231]
I think the [maya docs](https://github.com/krathjen/studiolibrary/blob/master/src/studiolibrarymaya/readme.md#animation-item-example) are incorrect.

Loading an animation needs a string for the ```option``` keyword and not ```animitem.PasteOption.ReplaceCompletely```.

**Comment by krathjen** [comment]
Hey @tokejepsen,

Thanks for submitting this issue.

The missing constant should now be fixed in version 2.4.9.

Please let me know how it goes,

Kurt

**Comment by tokejepsen** [comment]
Thanks @krathjen!

That fixed it.
