### ISSUE TITLE
double namespace not working anymore

### ISSUE THREAD

**Issue by liudger** [krathjen/studiolibrary#232]
In our pipeline we are using double namespaces char:name:.....
This was working with the older version of studio library. We needed to update to get the mirror function working for advanced skeleton. Now the library can't find the characters.  It says the name space doesn't exist.

**Comment by krathjen** [comment]
Hi @liudger,

Thanks for reporting this issue.

This should now be fixed in version 2.4.8.

https://github.com/krathjen/studiolibrary

Let us know how it goes.

Cheers,

Kurt

**Comment by liudger** [comment]
Issue resolved
