### ISSUE TITLE
Mirror issue face Advanced skeleton

### ISSUE THREAD

**Issue by liudger** [krathjen/studiolibrary#233]
We are working with advanced skeleton rigs. They have face controls that mirror wel. But advanced skeleton has also a seperate controlbox that doesn't mirror well.

![image](https://user-images.githubusercontent.com/4112111/57069444-fb825500-6cd4-11e9-8036-b36f3f641f2d.png)

Is there a works around for this issue?

**Comment by krathjen** [comment]
Hi @liudger,

Thanks for letting us know about this issue.

We will have a look in more detail but it may take some time.

Cheers,

Kurt

**Comment by liudger** [comment]
Maybe I can have a dev here look at it. What is your estimate time wise?

**Comment by krathjen** [comment]
Hey @liudger,

I just had a very quick look.

As you said, it is mirroring correctly, however, those controls should not be mirrored.

The only solution, for now, is to change the values for the controls in mirrortable.json file manually. The mirrortable.json file is created when you create a mirrortable item.

I think you will need to change all the values to "1" for each box face control except the eyes in the mirrortable.json.  See the example below.

I hope that makes sense.

Cheers,

Kurt


```json
    "ctrlBrow_L": {
      "mirrorAxis": [
        1, 
        1, 
        1
      ]
    }, 
```
```json
    "ctrlBrow_R": {
      "mirrorAxis": [
        1, 
        1, 
        1
      ]
    }, 
```

**Comment by liudger** [comment]
Thanks Kurt, I'll have a look

**Comment by liudger** [comment]
This works so for me. 
I don't know how you would solve this issue in general? Identify advanced skeleton controls?
