### ISSUE TITLE
Studio Library Not Working For My Maya 2019

### ISSUE THREAD

**Issue by rghu92** [krathjen/studiolibrary#234]
Hi, I have downloaded and used Studio Library for Maya 2015, 2016, 2017.

Recently upgraded to 2019 a week ago, but when opening Studio Library the interface is blank, I cannot add a folder, I can add a pose folder to import a .json file for my school rigs which works on Maya 2017 and older, but nothing in 2019 it simply opens a new blank window, again where I cannot create a folder or do anything or see any of the subfolders or poses.

Have also downloaded most of the versions on here and tested including the latest version available on here and having the same issues. That and all other versions works fine in the older Mayas but still unable to use it in 2019.

Any assistance would be greatly appreciated. Please find attached some screenshots including some errors in the script editor, if that helps.

![StudioLib_maya2019_01](https://user-images.githubusercontent.com/50601895/57662114-cdaae380-75e5-11e9-884f-b4b59c222336.jpg)
![StudioLib_maya2019_02](https://user-images.githubusercontent.com/50601895/57662115-cdaae380-75e5-11e9-8120-16f7fb8ac6c2.jpg)
![StudioLib_maya2019_03](https://user-images.githubusercontent.com/50601895/57662116-cdaae380-75e5-11e9-9c51-e9a6c5bdfdc2.jpg)
![StudioLib_maya2019_04](https://user-images.githubusercontent.com/50601895/57662117-cdaae380-75e5-11e9-808b-b0d2c383e96e.jpg)
![StudioLib_maya2019_05](https://user-images.githubusercontent.com/50601895/57662118-cdaae380-75e5-11e9-859a-1d80de772c69.jpg)
![StudioLib_maya2019_06](https://user-images.githubusercontent.com/50601895/57662119-ce437a00-75e5-11e9-8654-81eb346ebb03.jpg)

**Comment by krathjen** [comment]
Hi @rghu92,

Thanks for submitting this issue.

It looks like you're trying to run version "1.30.1" which is not supported in Maya 2019.

Have you tried the latest release from the following link (2.4.12)?

https://github.com/krathjen/studiolibrary/releases

Also, the installation process has also changed. Please see the following link.

https://github.com/krathjen/studiolibrary#installation

Let me know how you go.

Thanks,

Kurt

**Comment by rghu92** [comment]
Hi, 
I must have left the old studio library in my preferences for the screenshot images, but I did test the 2.4.10 in 2019 with no luck, the latest version v2.4.12 is working great for my 2019. Not sure if it was the installation method or those other versions. Don't want to change anything to find out as all is working for now which is happy days for me :)

Thank you for taking the time to reply and help me out.

**Comment by krathjen** [comment]
Hey @rghu92,

Thanks for letting us know! I'm glad to hear its working for you.

Cheers,

Kurt
