### ISSUE TITLE
Edit > Overwrite

### ISSUE THREAD

**Issue by tokejepsen** [krathjen/studiolibrary#238]
Would be convenient to have an option to overwrite an item by ```Edit``` > ```Overwrite```. It would simply take the naming and type of the item and ignore the overwriting dialog.

**Comment by krathjen** [comment]
Hey @tokejepsen,

Thanks for the suggestion! I've pushed this feature to the latest master.

It doesn't support animation items yet but let me know what you think and if you have any issues.

Thanks,

Kurt

**Comment by tokejepsen** [comment]
Getting an error when trying to add or overwrite a pose:

```
# Traceback (most recent call last):
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\studiolibrary\libraryitem.py", line 221, in overwrite
#     widget = self.showCreateWidget(self.libraryWindow(), item=self)
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\studiolibrarymaya\baseitem.py", line 74, in showCreateWidget
#     widget = cls.CreateWidgetClass(item=item, parent=libraryWindow)
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\studiolibrarymaya\basesavewidget.py", line 80, in __init__
#     self.setItem(item)
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\studiolibrarymaya\basesavewidget.py", line 172, in setItem
#     self.setThumbnail(item.thumbnailPath())
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\studiolibrarymaya\basesavewidget.py", line 478, in setThumbnail
#     shutil.copyfile(src, dst)
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\shutil.py", line 83, in copyfile
# IOError: [Errno 2] No such file or directory: u'c:/users/admin/appdata/local/temp/StudioLibrary/admin/thumbnail.png'
```

**Comment by krathjen** [comment]
Thanks @tokejepsen.

This should now be fixed in version 2.5.0.b3 (Latest master).

Let me know if you have any issues.

Cheers,

Kurt

**Comment by tokejepsen** [comment]
Yup, that works really well.

**Comment by krathjen** [comment]
Great! Thanks for letting me know.

**Comment by tokejepsen** [comment]
Should I close this, or wait for animation items support?

**Comment by krathjen** [comment]
yea, I think it might be nice to add support for animation items before closing this issue. Thanks.

**Comment by krathjen** [comment]
Hey @tokejepsen,

Hope you're well.

Just letting you know that this feature is now supported for the Animation Item in version 2.5.0.b28+

I hope that helps and please let me know if you have any issues.

Thanks,

Kurt

**Comment by tokejepsen** [comment]
Yup, that works really well. Great work!
