### ISSUE TITLE
Sync existing folders

### ISSUE THREAD

**Issue by tokejepsen** [krathjen/studiolibrary#239]
Having issues syncing existing folders into the database.

I'm copying the folders manually, but when syncing the item do not show up in the library.

**Comment by krathjen** [comment]
Hey @tokejepsen,

Thanks for submitting the issue. 

I can't seem to recreate this issue at the moment.

What OS, Maya and Studio Library version are you using?

Also, do any new items show up in the UI?

Cheers,

Kurt

**Comment by tokejepsen** [comment]
> What OS, Maya and Studio Library version are you using?

Windows 10, Maya 2019, Studiolibrary 2.4.12

> Also, do any new items show up in the UI?

When I export from the UI, poses and animation, they show up in the UI.

**Comment by krathjen** [comment]
Thanks for the information.

How deep are the folders from the root directory? There is a fixed recursive limit when searching the root directory. The default recursive limit is 3 levels deep. Could this be the issue?

You can change the limit in the config file.

Cheers,

Kurt

**Comment by tokejepsen** [comment]
Ahh, yes, that was the issue. Thanks!

**Comment by krathjen** [comment]
Great and sorry for the hidden feature. Hopefully, we can improve this.

**Comment by tokejepsen** [comment]
Maybe it should be part of the setting menu?

**Comment by krathjen** [comment]
I was thinking the same. I'll have a think about this. thanks again.

**Comment by tokejepsen** [comment]
Sorry for digging this issue up again, but I seem to have an issue syncing a mapped drive on Windows:
```
# Traceback (most recent call last):
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\studiolibrarymaya\baseitem.py", line 396, in selectContent
#     self.transferObject().select(namespaces=namespaces, **kwargs)
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\mutils\animation.py", line 401, in select
#     selectionSet.load(objects=objects, namespaces=namespaces, **kwargs)
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\mutils\selectionset.py", line 62, in load
#     self.validate(namespaces=namespaces)
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\mutils\transferobject.py", line 174, in validate
#     raise ValueError(msg)
# ValueError: The namespace "animation_transfer:old_rig" does not exist in the scene! Please choose a namespace which exists.
# Traceback (most recent call last):
#   File "C:\Users\admin\Desktop\pype-setup\repos\studiolibrary\src\studiolibrarymaya\basesavewidget.py", line 509, in accept
#     raise Exception("No folder selected. Please select a destination folder.")
# Exception: No folder selected. Please select a destination folder.
```
When selecting a drive for example ```Y:/```, the settings makes it ```Y:```. Dunno whether that could be the issue.

**Comment by tokejepsen** [comment]
Forgot to mention that any folder on the mapped drive works fine.

**Comment by krathjen** [comment]
Hey @tokejepsen,

Thanks for letting us know.

I'll try and have a look over the next few days.

Cheers,

Kurt

**Comment by krathjen** [comment]
Hey @tokejepsen,

I have pushed some changes to master (2.5.0.b13) which might fix this issue.

Please let me know how it goes.

Thanks,

Kurt

**Comment by tokejepsen** [comment]
Yup, that fixed it. Thanks @krathjen !
