### ISSUE TITLE
Name Field text is being crunched by UI. 

### ISSUE THREAD

**Issue by alelekita** [krathjen/studiolibrary#240]
On the newest updates, the 'Name' field text is very small, I can only fix that by resizing the entire window until it goes back to a normal size. Closing Maya doesn't retain my new window size.

**Comment by krathjen** [comment]
Hi @alelekita,

Thanks for submitting the issue.

Do you mind attaching a screenshot showing the issue regarding the name field text? 

Also, which Studio Library version are you using?

Cheers,

Kurt

**Comment by alelekita** [comment]
![Capture](https://user-images.githubusercontent.com/38712472/59054770-4994f600-8849-11e9-808e-6a3536513187.PNG)

The latest: 2.4.15
Maya: 2016 Sp6

**Comment by alelekita** [comment]
Kurt, 

I just got version 2.5.0.b3 and it has the same issue too.

**Comment by krathjen** [comment]
Great! Thanks for the information. Hopefully, we can look at this soon.

**Comment by krathjen** [comment]
Hi @alelekita,

Thanks again for submitting this issue.

This should now be fixed in version 2.5.0.b23+. 

Please let us know how it goes.

Cheers,

Kurt

**Comment by alelekita** [comment]
Hi Kurt! 

The issue with the text field is gone, thanks!

But now there is a bigger issue. I am getting this error when selecting any pose widget:

# Traceback (most recent call last):
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrary\librarywindow.py", line 425, in _itemSelectionChanged
#     self.setPreviewWidgetFromItem(item)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrary\librarywindow.py", line 1671, in setPreviewWidgetFromItem
#     item.showPreviewWidget(self)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrary\libraryitem.py", line 348, in showPreviewWidget
#     widget = self.previewWidget(libraryWindow)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrary\libraryitem.py", line 361, in previewWidget
#     widget = self.PreviewWidgetClass(item=self)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrarymaya\poseitem.py", line 46, in __init__
#     super(PoseLoadWidget, self).__init__(*args, **kwargs)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrarymaya\baseloadwidget.py", line 60, in __init__
#     self.setItem(item)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrarymaya\baseloadwidget.py", line 156, in setItem
#     formWidget.setSchema(item.loadSchema())
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrary\widgets\formwidget.py", line 236, in setSchema
#     widget.setData(data_)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrary\widgets\fieldwidgets.py", line 226, in setData
#     self.setValue(value)
#   File "C:\Users\amota\Documents\maya\scripts\studiolibrary-master\src\studiolibrary\widgets\fieldwidgets.py", line 1059, in setValue
#     self.widget().setCurrentText(self.listToString(value))
# AttributeError: 'PySide.QtGui.QComboBox' object has no attribute 'setCurrentText'

**Comment by alelekita** [comment]
Also, the right side of the menu doesn't load the option for the pose widget either.

**Comment by krathjen** [comment]
Thanks for the info.

The error was specific to Maya 2016 and should now be fixed in version 2.5.0.b24+.

Let me know how it goes.

Thanks,

Kurt

**Comment by alelekita** [comment]
Looks good! Thanks!!
