### ISSUE TITLE
Folder Contents Wont Display

### ISSUE THREAD

**Issue by virtualengineer** [krathjen/studiolibrary#242]
Hi, New User.
I am using Windows 10 and Studio Library 2.5.1 .
I have folders with Maya scene files and image files (tga etc).
I can not get any of the folder contents to display in your tool.
Even if I press they sync button, the folder contents won't display.

I tried it with Maya 2016, 2017 and 2018.
I tried creating a custom config file and set the file recursion to a high number (50).
I also tried adding the full path for the studio library source folder to my windows system path.

But, it still wont display the folder contents.

Are there any python package dependencies I should install ?

Does your tool require any System Environment variables to be set ?
PYTHON_HOME, PYTHON_PATH  etc ?

I would like to try using your tool.
Please let me know if there is a way to fix this.

Maya Script Editor Output:
```
# -----------------------------------
# Studio Library
# www.studiolibrary.com
# -----------------------------------

import os
import sys
    
if not os.path.exists(r'D:\Projects\Github\Maya\studiolibrary-2.5.1\src'):
    raise IOError(r'The source path "D:\Projects\Github\Maya\studiolibrary-2.5.1\src" does not exist!')
    
if r'D:\Projects\Github\Maya\studiolibrary-2.5.1\src' not in sys.path:
    sys.path.insert(0, r'D:\Projects\Github\Maya\studiolibrary-2.5.1\src')
    
import studiolibrary
studiolibrary.main()
```

**Comment by krathjen** [comment]
Hi @virtualengineer,

Thank you for submitting the issue.

At the moment the Studio Library will only show ".anim", ".pose", ".sets" and ".mirror" items that have been created using Maya.

Have you used the Studio Library before with other formats?

Thanks,

Kurt

**Comment by virtualengineer** [comment]
Hi @krathjen ,
Thanks for responding. I am a first time user. 
Sorry, I thought the tool would show .ma maya files and image files in the file view.
I tried making a few pose files and they displayed properly.
I will take more time to learn how to use your tool.

Thanks
