### ISSUE TITLE
Implement UNC paths

### ISSUE THREAD

**Issue by alamoureux** [krathjen/studiolibrary#246]
It seems that UNC path doesn't work.
If I set the path on a network folder, it creates items inside the current working directory + the given network path.

**Comment by krathjen** [comment]
Hi @alamoureux,

Thanks for letting us know.

I just pushed some changes which might fix your issue.

Please download the latest version (2.6.2) from the master branch.

https://github.com/krathjen/studiolibrary

You may need to click the refresh button.

Let me know how that goes.

Thanks,

Kurt

**Comment by alamoureux** [comment]
Seems to work well, thanks a lot!
Arnaud
