### ISSUE TITLE
Error 5 Access denied

### ISSUE THREAD

**Issue by trp35** [krathjen/studiolibrary#247]
Hi, Been using studioLibrary for many years.  Fantastic tool! So much appreciated.  Recently I been getting Error 5: Access denied when trying to save a pose.  Any thoughts on what is causing that?  Thanks much and again thanks for a great tool.

**Comment by krathjen** [comment]
Hi @trp35,

Thanks for the comment.

This sounds like a permissions issue when Studio Library is trying to save a file to disc.

I will need more information to understand the issue better.

Which OS are you using?
Which Maya version are you using?
What version of Studio Library are you using?
Are trying to use this in a studio environment?

Thanks,

Kurt

**Comment by trp35** [comment]
Hi Kurt,

Windows 10
Maya 2018 and 2019
v 2,4,12
Yes in a studio environment with multiple animators sharing libraries. Has
not seemed to be an issue until recently.
Not real tech savvy, but I assume that the database.json file in
/.studiolibrary is the file that stores everything and if I want to add a
folder, delete a pose, etc-- that file needs to be editable.  In our case,
I would need to check out that file to do that.  Recently, I just get the
Access denied error when working in studioLibrary.

Any thoughts will be greatly appreciated.  Again, I love your tool-- by far
the best pose/animation library tool I've ever used.

Thanks much!
-Ted

**Comment by krathjen** [comment]
Hey @trp35,

Thanks for the information.

Have you tried Studio Library version 2.6.3? 

Cheers,

Kurt

**Comment by trp35** [comment]
Thanks again for the reply.  I wound deleting every folder of studioLibrary
that I had on my computer and installed a fresh version (wasn't sure if
there was a way to uninstall) not the latest, but a recent one.  That has
seemed to remedy the issue I was having.

Is there a way to uninstall?

Thanks,
Ted

**Comment by krathjen** [comment]
Hi @trp35,

Thanks for letting us know.

At the moment you could just delete the unzipped studiolibrary folder to uninstall.

Hope that helps,

Kurt
