### ISSUE TITLE
When updating from 2.3.6 (think that was the one at least), lost existing animations

### ISSUE THREAD

**Issue by martin8910** [krathjen/studiolibrary#249]
Hi!

Great tool :)
When I just upgraded to 2.6.3 my existing animations from earlier versions are no longer recognized, even if the path is maintained in settings, and it asked me now to "Move to trash" when I choose to create a new folder with the same name. Is this a known issue?

**Comment by krathjen** [comment]
Hey @martin,

Thanks for your comment.

Your existing animations from version 2.3.6 should work with 2.6.3. I'm testing we much older animation clips and they seem to work fine, so it could be a syncing issue. 

Have you tried clicking the sync/refresh button in the settings menu?

Cheers,

Kurt

**Comment by martin8910** [comment]
Hi again Kurt!

Thanks a lot for your email.
You are absolutely right, a simple "Sync" solved my issues.
Should have read the documentation more carefully afterward :D

All the best and thanks for an amazing tool!

/Martin

**Comment by krathjen** [comment]
That's great! I'm glad to hear its working for you. :)
