### ISSUE TITLE
Raising exceptions on an expected user interaction

### ISSUE THREAD

**Issue by boredstiff** [krathjen/studiolibrary#250]
https://github.com/krathjen/studiolibrary/blob/master/src/studiolibrarymaya/basesavewidget.py#L331

This causes our internal Sentry logging to catch and log this every time someone presses Cancel.

Thanks.

**Comment by krathjen** [comment]
Thanks @boredstiff,

This should now be fixed on the master branch.

Let me know if you have any issues.

Cheers,

Kurt

**Comment by boredstiff** [comment]
Thanks Kurt.
