### ISSUE TITLE
install.gif Already old  

### ISSUE THREAD

**Issue by Songxwn** [krathjen/studiolibrary#254]
You need to update to the official website new.
 
https://www.studiolibrary.com/images/install.gif

**Comment by krathjen** [comment]
That's strange, I just downloaded the latest version and they were both there.

You can also see it here...

https://github.com/krathjen/studiolibrary/blob/master/install.py

Which version did you download?

Cheers,

Kurt

**Comment by krathjen** [comment]
Closing this ticket.

Please let us know If you're still having issues with the latest version.

Thanks,

Kurt
