### ISSUE TITLE
[Maya 2020 - Qt5.12.3] QMessageBox.StandardButton error

### ISSUE THREAD

**Issue by wgergely** [krathjen/studiolibrary#260]
The new Qt Maya 2020 is shipped with seems to be pickier with types and StudioLibrary fails to show messageboxes. The offending module seems to be *studiolibrarymaya\basesavewidget.py*, replacing `QtWidgets.QMessageBox.StandardButtons` with `QtWidgets.QDialogButtonBox.StandardButtons` seems to fix the issue.

Any chance you could implement this?
Cheers!

**Comment by krathjen** [comment]
Hi @wgergely,

Thanks for submitting this issue.

I'll try and have a look soon.

Cheers,

Kurt

**Comment by krathjen** [comment]
Hi @wgergely ,

I just pushed version 2.7.0.b7 to master which should fix this issue.

Please download and let me know how it goes.

Thanks,

Kurt
