### ISSUE TITLE
Windows network paths

### ISSUE THREAD

**Issue by ds0656** [krathjen/studiolibrary#270]
When using a network path on windows the path is not correctly resolved for some operations.

Correct path: \\\remote-pc\path
Wrong path: \remote-pc\path

In the log I see it is using the wrong path when saving animations, resulting in items being saved to c:\remote-pc\path

It uses the correct path when accessing the database.json file

Version 2.7.1

**Comment by krathjen** [comment]
Hi,

Thanks for letting us know.

We will try and have a look.

Kurt

**Comment by luke674** [comment]
has there been any update on this as I am having the same issue. Studiolibrary loads the folders from network path along with whats inside them but then when a folder is selected they go blank. If I try to create a pose or animation it then saves it to  c:\remote-pc\path

Any advice would be greatly appreciated.

**Comment by krathjen** [comment]
If you're still experiencing issues with the latest version, please either reopen this ticket or create a new one. thank you.
