### ISSUE TITLE
Documentation for mutils truncated on latest commit

### ISSUE THREAD

**Issue by geordiemartinez** [krathjen/studiolibrary#322]
I was looking at the documentation for mutils, how to save an animation, how to load an animation, etc. and when I refreshed the github page they instructions were gone.

**Comment by krathjen** [comment]
Thanks for the comment.

The mutils docs haven't been updated for a long time. Maybe you were looking at the following page?

https://github.com/krathjen/studiolibrary/tree/master/src/studiolibrarymaya

**Comment by geordiemartinez** [comment]
ah yes. apologies!
Love this tool by the way!!!
