### ISSUE TITLE
python 3 print commands syntax error

### ISSUE THREAD

**Issue by rophelan21** [krathjen/studiolibrary#333]
I fixed a few of them, but seems like they are all over
print results ==> print (results)

# Error: invalid syntax
# Traceback (most recent call last):
#   File "<maya console>", line 16, in <module>
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
#   File "C:\Users\desig\Documents\maya\scripts\studiolibrary\src\studiolibrary\__init__.py", line 29, in <module>
#     from studiolibrary.libraryitem import LibraryItem
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
#   File "C:\Users\desig\Documents\maya\scripts\studiolibrary\src\studiolibrary\libraryitem.py", line 23, in <module>
#     import studiolibrary.widgets
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
#   File "C:\Users\desig\Documents\maya\scripts\studiolibrary\src\studiolibrary\widgets\__init__.py", line 18, in <module>
#     from .messagebox import MessageBox, createMessageBox
#   File "C:\Program Files\Autodesk\Maya2022\Python37\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
#     return original_import(name, *args, **kwargs)
#   File "C:\Users\desig\Documents\maya\scripts\studiolibrary\src\studiolibrary\widgets\messagebox.py", line 717
#     print studiolibrary.widgets.MessageBox.input(
#                       ^
# SyntaxError: invalid syntax #

**Comment by krathjen** [comment]
Hi @rophelan21,

Have you tried version 2.9.6+?

https://github.com/krathjen/studiolibrary/releases/tag/2.9.6.b1

Thanks,

Kurt

**Comment by rophelan21** [comment]
Thanks, yes, this version works for me. Thanks!
