### ISSUE TITLE
Do not see any pose / animation inside Studio Library

### ISSUE THREAD

**Issue by markC85** [krathjen/studiolibrary#337]
Working with 2.7.1 on Maya 2022 running python 2.7 I do not see any animation I save / poses. When I generate the pose I notice the library creates the test_pose.pose folder / then thumbnail file / pose.json file just fine.

But inside the UI I do not see anything.
![image](https://user-images.githubusercontent.com/42453770/123507702-1425f580-d628-11eb-8f77-c97deb1901f2.png)

![image](https://user-images.githubusercontent.com/42453770/123507712-30299700-d628-11eb-96f3-63f528e0837e.png)

I tried taking one of my old poses that shows up just fine and if I change the folder name to match it then the image shows up inside the library but that's it.

**Comment by gramirez16** [comment]
I don't know if you need an answer still or what not. However you have "PHONE" in the search bar which is probably making none of the poses appear.

**Comment by markC85** [comment]
well great thanks @gramirez16 that was the problem I was able to copy my pose I will do some more testing tonight but I am going to close this issue out now...
