### ISSUE TITLE
'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128)

### ISSUE THREAD

**Issue by Salmonart** [krathjen/studiolibrary#349]
# Error: UnicodeDecodeError: file D:\Documents\maya\scripts\studiolibrary-2.9.6.b3\src\studiolibrary\utils.py line 574: 'ascii' codec can't decode byte 0xe0 in position 3: ordinal not in range(128) #

**Comment by Salmonart** [comment]
Hello team!
I have that error since a few weeks, impossible to launch SL whatever the version I use with Maya 2020.4

**Comment by Salmonart** [comment]
Windows 10

**Comment by zuyi53** [comment]
add this 

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

**Comment by krathjen** [comment]
A similar issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary.com

Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
