### ISSUE TITLE
Maya 2022 SyntaxError

### ISSUE THREAD

**Issue by ilookedeverywhere** [krathjen/studiolibrary#353]
# Error: SyntaxError: file /Applications/Autodesk/maya2022/Maya.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py line 142: invalid syntax # 
select -cl  ;

When trying to use the shelf button, this error is given and Studio Library does not open.

**Comment by krathjen** [comment]
This should now be fixed with the latest version 2.9.11
