### ISSUE TITLE
Maya 2022 'Error while saving' 'charmap'

### ISSUE THREAD

**Issue by ruecroft** [krathjen/studiolibrary#360]
Hello,
Apologies if this topic is already discussed elsewhere. I wasn't able to find an answer.

Using Studio Library 2.9.6.b3, Maya 2022, Windows 11

While saving animation from my rig I get `Error while saving: 'charmap' codec can't decode byte 0x8d in position 871: character maps to <undefined>`

If I open the same file in Maya 2018 I can save the animation without a problem, so the Maya version seems to be the only variable that is different. 

Studiolibrary.com says "Support for Maya 2016, 2017, 2018 and 2019," but then I saw a user comment that they use it with Maya 2022 daily. Is there some trick to get it working? 

Thanks for this awesome tool and for any suggestions!

**Comment by lisab1** [comment]
Hi! As indicated by tepenrod here : https://github.com/krathjen/studiolibrary/issues/345, the issue seems to come from the function _cleanMayaFile()_ of src/mutils/animation.py. The _open()_ function has been updated in python 3 which is used by Maya 2022 (http://python-notes.curiousefficiency.org/en/latest/python3/text_file_processing.html) in order to detect encoding problem.
One solution that seems to work for me is to process the file in binary in order to avoid defining an encoding codec. In src/mutils/animation.py, you can try to modify the _cleanMayaFile()_ definition as following:
```
with open(path, "rb") as f:
    for line in f.readlines():
        if not line.startswith(bytes("select -ne",'ascii')):
            results.append(line)
        else:
            results.append(bytes("// End",'ascii'))
            break

with open(path, "wb") as f:
    f.writelines(results)
```
Hope it this will help!

**Comment by Yifat3D** [comment]
So I had the same issue... while I was on maya 2022.
I tested maya 2020 as well, and it didn't happen there, so I figured it was something with the prefs. Long story short, it was python 3's fault. 
Once I've set my maya 2022 to run python 2 instead- the library worked just fine.
To do that I used the 1st option from this guide- 
https://matiascodesal.com/blog/how-to-launch-maya-2022-with-python-2-if-you-are-not-ready-for-python-3/

**Comment by gabrieljreed** [comment]
Ran into a similar error in Maya 2023 when trying to save out animations using MB files. It seems like the `cleanMayaFile` function in `animation.py` tries to manually parse the Maya file, which fails when it tries to use a binary file. I just added this snippet at the beginning of the function to skip this parse on any binary files. 

```python
        file_extension = os.path.splitext(path)[1]
        if file_extension == ".mb":
            logger.info("Binary file detected: " + path + ". Skipping clean.")
            return
```

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary.com 

Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
