### ISSUE TITLE
Can't Save Animation In Maya 2022.3

### ISSUE THREAD

**Issue by studiolibraryranger** [krathjen/studiolibrary#365]
Hi there, I'm unable to save animation in Maya via Studio Library. I'm getting the following error:
'charmap' codec can't decode byte 0x90 in position 2580: character maps to <undefined>

I know a few people have posted regarding it - Has anyone found a solution yet?

It's such a cool tool, sad it's falling apart.

**Comment by mantis3d** [comment]
I found a solution, it's working for me.

open studiolibrary-2.9.6.b3\src\mutils\animation.py, in line 545, it's
**with open(path, "r") as f:**

change to
**with open(path, "r",encoding='utf-8') as f:**

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary.com 

Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
