### ISSUE TITLE
Cannot save animations in Maya 2022

### ISSUE THREAD

**Issue by HalicalBailey** [krathjen/studiolibrary#370]
Hi! I'm using Maya 2022 and using studiolibrary-2.9.6.b3 on Windows 11. I'm currently animating a run cycle in a separate scene so I can use Studio Library to save an animation and import it into a different scene.

however...

Studio Library is being mean and will not allow me to save the animation at all due to an error I'm trying to figure out.
I keep getting two different errors:

'charmap' codec can't decode byte 0x90 in position 2126: character maps to <undefined>
and,
{errno 2} No such file or directory: 'C:/User/AppData/Local/Temp/StudioLibrary/user/thumbnail/thumbnail.0000.jpeg'

I can't believe this nonsense.

Here is some photo proof of said errors.
![StudioLibraryAnim Error 01](https://user-images.githubusercontent.com/101610747/158290267-2a960252-f7b3-4a55-bae1-45a008912501.png)
![StudioLibraryAnim Error 02](https://user-images.githubusercontent.com/101610747/158290269-6e671fa6-00e3-47a1-9fee-8d1fbe204956.png)

I am an animator and not a coder so I am struggling to try and figure this out on my own.
I don't want any of my animations saved to a TEMP file, only my where my directory is saving them to VIA settings.
and more importantly, I want to save my animations in general!!!

Can anyone please help me with this issue? I would be super grateful.

**Comment by darrenplace** [comment]
@HalicalBailey I was getting the same errors, but was able to circumvent them by [running Maya in Python2 mode](https://matiascodesal.com/blog/how-to-launch-maya-2022-with-python-2-if-you-are-not-ready-for-python-3/)!

Ideally these bugs could be patched soon as several other pipeline tools are dropping support for Py2 😞

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary.com 

Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
