### ISSUE TITLE
receiving a codec error when attempting to save anim clip

### ISSUE THREAD

**Issue by stevebGithub** [krathjen/studiolibrary#390]
'charmap' codec can't decode byte 0x8f in position 6351: character maps to <undefined>

this is occuring even if i dont use a thumbnail. 

i tested an older clip saved thats in the file system and it worked to apply existing anim, just not creating new ones

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary. Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
