### ISSUE TITLE
Issue while saving the animation in Studio Library

### ISSUE THREAD

**Issue by Gunny2502** [krathjen/studiolibrary#392]
Hi, I am using 2.9.6.b3 Studio Library. I am having this error (attached screenshot) while saving animation. I have tried with Maya 2018, 2020, and 2022, and with different files, and rigs but same issue. I have tried reinstalling SL, resetting it, and also resetting Maya preferences. Nothing is working. Please help me.
![SL](https://user-images.githubusercontent.com/112423321/187269695-ba96739d-a402-4a3d-8673-f8aeb6f0c0e6.png)

**Comment by krathjen** [comment]
A similar issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary.com

Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
