### ISSUE TITLE
'charmap' codec 

### ISSUE THREAD

**Issue by stevebGithub** [krathjen/studiolibrary#395]
Hello, 

so Ive started running into this issue (about 3 months now) - when go to create an animation capture, if the file type is set to mayaBinary i get this:

'charmap' codec  can't decode byte 0x90 in position 740: character maps to <undefined>

obviously this is fine if im able to save my file to match but on systems where the default structure has been .mb i havent been able to use StudioLibrary as i dont have a solution

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary. Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
