### ISSUE TITLE
Folders and assets not being found/synced

### ISSUE THREAD

**Issue by KnightAnim** [krathjen/studiolibrary#396]
Hi, 

I've had to reorganise folders recently for a project I'm working on. Only a certain level of folders and assets are now being found.

From googling I found an issues from years ago that Studio Library only looks 4 folders deep for assets and that you need to change it in the config to look deeper. I can't seem to find the config to do that, if that is still even a problem?

My folders and assets are 5 folders deep, so I assume that it's still the case. What should I do in order to sync further down the folder path?

Using 2.9.6.b3. Maya version 2020.4. Windows 10.

Kind regards

**Comment by nojule** [comment]
no feedback on this?

**Comment by krathjen** [comment]
Hi, have you tried the latest version?

https://github.com/krathjen/studiolibrary/releases/tag/2.9.11

**Comment by KnightAnim** [comment]
I have and I believe this does allow for 5 levels of folder depth now.

That being said, is there a way we can increase this? Is there a reason it's limited to 5? I understand 5 is pretty deep for most people, but using this on a shared project means 5 levels isn't all that much.

Thanks for the response!

**Comment by krathjen** [comment]
You can control the recursive search depth via code or the config.json. The main reason for this is if someone accidentally chooses a library folder that has a huge number of subfolders or files which would slow down the indexing process. We might increase the default limit again.

config example:
https://github.com/krathjen/studiolibrary/tree/master/config

code example:
``` python
import studiolibrary
studiolibrary.config.set("recursiveSearchDepth", 6)
studiolibrary.main()
```

**Comment by KnightAnim** [comment]
Ah that's great, I used the code option and it's working, thank you! 
I think I had read this before somewhere but it hadn't made sense until you put it like that.

For others, if it isn't clear, edit the Studio Library icon on your Shelf in Maya and replace the very bottom 2 lines of code with the 3 lines of code in Krathjen's code example above this comment. Changing 6 to whatever you need.

Thanks @krathjen !
