### ISSUE TITLE
Blend slider issue

### ISSUE THREAD

**Issue by Lohult** [krathjen/studiolibrary#398]
When  blending in a pose (35 controls selected in my case) the blend slider is slow to update to user input. Another issue is you would drag and let go when you find your sweet spot but then the slider continues to drag by itself regardless of mouse up event. Ideally the mouse up event should exit the slider movement regardless of where the pointer was dragging to? I'm guessing that's what is going but hopefully my description of the problem is clear. Thanks.

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket. Thank you for letting us know.
