### ISSUE TITLE
'charmap' codec can't decode byte 0x81 in position 852: character maps to <undefined>

### ISSUE THREAD

**Issue by MUZAMMILJ** [krathjen/studiolibrary#400]
When I click to save my animation popup "'charmap' codec can't decode byte 0x81 in position 852: character maps to <undefined>"
using maya 2022 with updated libray version
![Problem](https://user-images.githubusercontent.com/121419106/209510609-c9b9080a-6cee-4249-9b79-72f4d8089617.png)

**Comment by Tonire** [comment]
Sorry for reviving this old issue, but I have the same problem. Did you find a solution? 
Thanks :)

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary. Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
