### ISSUE TITLE
Capture thumbnail not working

### ISSUE THREAD

**Issue by nuzzledark** [krathjen/studiolibrary#404]
I have studio library installed in Maya 2023 and the capture thumbnail tool isn't working. It shows my character in the capture screen but when I click on capture the resulting thumbnail is a grey square. Any idea why this is happening?

![image](https://user-images.githubusercontent.com/66137783/217935690-75d17538-8481-4919-b0e1-b52b3d3eeb76.png)

**Comment by pava0ne** [comment]
I'm facing the same issue, did you manage to solve it? Thanks!
