### ISSUE TITLE
Animation is not being saved - Item error - File not found

### ISSUE THREAD

**Issue by paschwa** [krathjen/studiolibrary#407]
When I save an animation in studio library 2.9.6.b3 with Maya 2023.3  , it seemingly saves it (*.anim file in studio library ui is being created).

But when I want to load it, "Item Error - File not Found" window appears.

Inside the "*.anim" folder in windows explorer no maya file with animation was created, only thumbnails, json and sequence folder.

I tried to save as ascii or binary.

No errors appear in log when saving the animation.

![image](https://user-images.githubusercontent.com/125883653/220106919-0ffa35cb-eddb-4e0b-807f-5643dc0bb817.png)

**Comment by paschwa** [comment]
Sorry just noticed Maya 2023 is not supported yet. Will change to Maya 2022 for now, as Studio Library is such an important tool in my pipline :)

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket. Thanks for letting us know.

www.studiolibrary.com
