### ISSUE TITLE
Cannot load animation using non-ascii paths.

### ISSUE THREAD

**Issue by SajidAliMansoori** [krathjen/studiolibrary#409]
while I apply animation to character so this error generate, (Cannot load animation using non-ascii paths.)
how to solve this

**Comment by azagoruyko** [comment]
I tried to comment the following lines in `studiolibrary-2.9.6.b3\src\mutils\animation.py` on 505 line.

```
'''
if not self.isAscii(self.mayaPath()):
    msg = "Cannot load animation using non-ascii paths."
    raise IOError(msg)
'''
```
It seems to work.

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket. Thanks for letting us know.

www.studiolibrary.com
