### ISSUE TITLE
Error More then one object matches name 

### ISSUE THREAD

**Issue by nielsmedemblik** [krathjen/studiolibrary#417]
Hi!

With a few rigs in our production the studio library shows this error on saving an animation(sometimes it also reports more 'CURVE1', ''CURVE2' etc.) Saving a pose goes fine.  I can confirm that there are no objects with the same name in the rig.

![studiolibr_error_01](https://github.com/krathjen/studiolibrary/assets/23041346/c86721d7-8e21-47b1-bf2c-1b61eef046bc)

Also after this error appears a bunch of nodes have been added to the rig. I turned of the reference in this image so you can see what is added:

![curves](https://github.com/krathjen/studiolibrary/assets/23041346/f177a633-7c1b-4659-aa1c-6f3d28323cb0)

does anyone have a clue what might be happening?

**Comment by nielsmedemblik** [comment]
The curves seem to be created by the animation.py

`            for name in objects:
                if maya.cmds.copyKey(name, time=(start, end), includeUpperBound=False, option="keys"):
                    dup_node = self._duplicate_node(name, "CURVE")
                    # dup_node, = maya.cmds.duplicate(name, name="CURVE", parentOnly=True)`

**Comment by vil13** [comment]
Have this issue also . I ended up dropping down to 2.9.6.b3

**Comment by nielsmedemblik** [comment]
In our case the rigs contained joints with nurbsCurve Shapes as their child. The plugin didnt respond well to that. After removal it was fixed.
