### ISSUE TITLE
When saving new animation - TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tamkiraly** [krathjen/studiolibrary#419]
Tried to do nullchecks in mutils.animation functions, but just ended up in a loophole. Has anyone encountered this issue?

`# Traceback (most recent call last):
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\studiolibrarymaya\basesavewidget.py", `line 448, in accept
`#     self.save(path=path, thumbnail=thumbnail)
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\studiolibrarymaya\basesavewidget.py", `line 470, in save
`#     item.safeSave(
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\studioqt\decorators.py", line 24, in wrapped
`#     return fn(*args, **kwargs)
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\studiolibrary\libraryitem.py", line 655, in `safeSave
`#     self.save(*args, **kwargs)
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\studiolibrarymaya\animitem.py", line 264, in save
`#     mutils.saveAnim(
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\mutils\animation.py", line 130, in saveAnim
`#     anim.save(
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\mutils\decorators.py", line 42, in wrapped
`#     ret = fn(*args, **kwargs)
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\mutils\decorators.py", line 55, in wrapped
`#     return fn(*args, **kwargs)
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\mutils\decorators.py", line 133, in wrapped
`#     return fn(*args, **kwargs)
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\mutils\decorators.py", line 102, in wrapped
`#     return fn(*args, **kwargs)
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\mutils\animation.py", line 645, in save
`#     dup_node = self._duplicate_node(name, "CURVE")
`#   File "D:\Mesharray\downloaded models\studiolibrary-2.9.11\studiolibrary-2.9.11\src\mutils\animation.py", line 573, in _duplicate_node
`#     duplicated_node = maya.cmds.listRelatives(duplicated_node,
`# TypeError: 'NoneType' object is not subscriptable

**Comment by Sixxmahmud** [comment]
Meet too but i cant seem to find a solution, for me its hik rig

**Comment by justifun** [comment]
Same issue here when saving an animation clip

**Comment by krathjen** [comment]
Hi, 

This should now be fixed in version 2.9.12. 

You just need to download it from the main branch.

https://github.com/krathjen/studiolibrary

Click "code" -> "download ZIP"

Cheers,

Kurt

**Comment by krathjen** [comment]
This is was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary.com

Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
