### ISSUE TITLE
Maya 2023 is unable to save animation

### ISSUE THREAD

**Issue by erickim9682** [krathjen/studiolibrary#421]
Hello, Studiolibrary (release 2.9.11) is unable to save animation in Maya 2023. I sent a screenshot of the error that I am getting. Does anybody know any way to fix this?

![studio libarry bug](https://github.com/krathjen/studiolibrary/assets/38885435/f4581be0-1da5-40f6-a37d-7ee3a6adec7e)

**Comment by krathjen** [comment]
A similar issue was addressed in a recent release. Try downloading the latest version (v2.13.1) from the website, and if the issue persists, please reopen the ticket. Thank you for letting us know.
