### ISSUE TITLE
Freeze during blend action

### ISSUE THREAD

**Issue by vchax** [krathjen/studiolibrary#424]
I contact you because we constantly suffer Maya freeze when we do a blend selection with Studio Lib.
We can wait till 5 minutes before Maya is operational again.

On our new animated movie we use :
- Centos 7.9
- maya2020.4-update-x64
- studiolibrary-2.9.6.b3

The workstations have this configuration :
- RAM 128G
- Intel(R) Core(TM) i9-13900KF
- Geforce 3080

We didn’t find informations in the logs, the Maya scene isn’t so easy, the RAM is not full.
We only have 1 cpu thread at 100% during the blend action.
So we ask you if you have an idea because for the moment we are stuck.
Else I tried to send an email at support@studiolibrary.com but this email does not exist anymore. 

Let me know if you need more informations.
Thank you.

**Comment by krathjen** [comment]
This issue was resolved. Thanks again for your help on this one.
