### ISSUE TITLE
utf-8' codec can't decode byte 0xe4 in position 4: invalid continuation byte

### ISSUE THREAD

**Issue by jdobra** [krathjen/studiolibrary#427]
When saving animations in Studio Library we get this error
utf-8' codec can't decode byte 0xe4 in position 4: invalid continuation byte

We are using MAC OS may be related to python 3 
<img width="697" alt="MicrosoftTeams-image" src="https://github.com/krathjen/studiolibrary/assets/117233493/57baaece-7a0f-4153-886d-811b0502c32d">

**Comment by lucasridley** [comment]
I've ran into the same issue with a student using Maya 2024.1 on a windows, with a slightly different message. We've tested it on a simple polygon sphere:
<img width="647" alt="Screenshot 2023-07-23 171813" src="https://github.com/krathjen/studiolibrary/assets/140336450/7a9baa8f-e32e-49cf-bc73-3dbb258e0e09">

**Comment by krathjen** [comment]
Hi,

Thanks for the information.

Please try version 2.10.7+ from the following link.

https://github.com/krathjen/studiolibrary

Cheers,

Kurt

**Comment by JasonDobra** [comment]
Thanks Kurt, 

We'll give this a go. 

Jason

**Comment by krathjen** [comment]
This issue was addressed in a recent release. Try downloading the latest version from the website, and if the issue persists, please reopen the ticket or contact support@studiolibrary. Thank you for letting us know.

[www.studiolibrary.com](http://www.studiolibrary.com/)
