### ISSUE TITLE
Add support for Maya 2017 workspaces

### ISSUE THREAD

**Issue by krathjen** [krathjen/studiolibrary#9]
A new mayalibrarywidget.py should be created and used instead of the dockwidgetmixin.py.

**Comment by kalemas** [comment]
@krathjen tell me please where i have to base this change? I like your refactoring change for 2.xx, it easier to understand of how it works. But i m sure you would like it to be available for 1.xx series.

**Comment by krathjen** [comment]
Hey @kalemas, 

I think it would be better to rebase to the "refactor/studiolibrary" branch. We will probably phase out 1.3x pretty soon.

We could also rename the branch to "dev/studiolibrary2". what do you think?

Note that version 2 is still compatible with all items created after mid-2014. 

Cheers,

Kurt

**Comment by krathjen** [comment]
This has now been added in version 2.0.0b2.

Note: Version 2.0.0b2 no longer supports Maya 2016 and earlier.

Thanks for adding this Kalemas! :)
